<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-18 at 21:38:39.
 */
class InputTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Input
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Input;
		$_GET['test'] = 'test';
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * Generated from @assert ($_GET, 'test') [==] "test".
	 *
	 * @covers Input::get
	 */
	public function testGet()
	{

		$this->assertEquals(
		"test", \Input::get($_GET, 'test')
		);
	}

	/**
	 * Generated from @assert ('POST,GET', 'test,test') [==] "test".
	 *
	 * @covers Input::get
	 */
	public function testGet2()
	{

		$this->assertEquals(
		"test", \Input::get('POST,GET', 'test,test')
		);
	}

	/**
	 * @covers Input::ip
	 * @todo   Implement testIp().
	 */
	public function testIp()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::normalizeRequest
	 * @todo   Implement testNormalizeRequest().
	 */
	public function testNormalizeRequest()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::canConfig
	 * @todo   Implement testCanConfig().
	 */
	public function testCanConfig()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::stripSlashes
	 * @todo   Implement testStripSlashes().
	 */
	public function testStripSlashes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::getModule
	 * @todo   Implement testGetModule().
	 */
	public function testGetModule()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::getMethod
	 * @todo   Implement testGetMethod().
	 */
	public function testGetMethod()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::getPage
	 * @todo   Implement testGetPage().
	 */
	public function testGetPage()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::getFunction
	 * @todo   Implement testGetFunction().
	 */
	public function testGetFunction()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::isReferer
	 * @todo   Implement testIsReferer().
	 */
	public function testIsReferer()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::text
	 * @todo   Implement testText().
	 */
	public function testText()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::keywords
	 * @todo   Implement testKeywords().
	 */
	public function testKeywords()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::description
	 * @todo   Implement testDescription().
	 */
	public function testDescription()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::quote
	 * @todo   Implement testQuote().
	 */
	public function testQuote()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Input::filter
	 * @todo   Implement testFilter().
	 */
	public function testFilter()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}
}