<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-12-12 at 22:42:39.
 */
class ValidatorTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Validator
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Validator;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * Generated from @assert ('admin@localhost.com') [==] true.
	 *
	 * @covers Validator::email
	 */
	public function testEmail()
	{

		$this->assertTrue(
		\Validator::email('admin@localhost.com')
		);
	}

	/**
	 * Generated from @assert ('admin@localhost') [==] true.
	 *
	 * @covers Validator::email
	 */
	public function testEmail2()
	{

		$this->assertTrue(
		\Validator::email('admin@localhost')
		);
	}

	/**
	 * Generated from @assert ('ทดสอบ@localhost') [==] false.
	 *
	 * @covers Validator::email
	 */
	public function testEmail3()
	{

		$this->assertFalse(
		\Validator::email('ทดสอบ@localhost')
		);
	}

	/**
	 * Generated from @assert ('admin@ไทย') [==] true.
	 *
	 * @covers Validator::email
	 */
	public function testEmail4()
	{

		$this->assertTrue(
		\Validator::email('admin@ไทย')
		);
	}

	/**
	 * @covers Validator::isImage
	 * @todo   Implement testIsImage().
	 */
	public function testIsImage()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
		'This test has not been implemented yet.'
		);
	}
}